spring:
  profiles:
    active: prod
---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:taco
    driver-class-name: org.h2.Driver
    username: taco
    password: taco
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/taco-cloud?serverTimezone=Europe/Warsaw
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user_taco
    password: taco
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

